---
pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - base=master
      - author~=github-actions
      - check-success-or-neutral=Analyse
      - check-success-or-neutral=Check code quality
      - check-success-or-neutral=CodeQL
      - check-success-or-neutral=Deadpendency Check
      - check-success-or-neutral=GitHub Actions
      - check-success-or-neutral=Python Source Analyzer
      - check-success-or-neutral=Scan-Build
      - check-success-or-neutral=Security Audit for Infrastructure
    actions:
      merge:
        method: merge
        strict: smart
  - name: automatic merge for Dependabot pull requests
    conditions:
      - base=master
      - author~=dependabot
      - check-success-or-neutral=Analyse
      - check-success-or-neutral=Check code quality
      - check-success-or-neutral=CodeQL
      - check-success-or-neutral=Deadpendency Check
      - check-success-or-neutral=GitHub Actions
      - check-success-or-neutral=Python Source Analyzer
      - check-success-or-neutral=Scan-Build
      - check-success-or-neutral=Security Audit for Infrastructure
    actions:
      merge:
        method: merge
        strict: smart
  - name: warn on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: "@{{author}} this pull request is now in conflict 😩"
      label:
        add:
          - conflict
